[package]
name = "csv_transactions"
version = "0.1.0"
authors = ["Christian Ravn <christian.ravnen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
